#!/bin/sh

  #####  #     #  #####  ######   #####  
 #     # ##    # #     # #     # #     # 
 #       # #   # #       #     # #       
 #       #  #  #  #####  ######   #####  
 #       #   # #       # #     #       # 
 #     # #    ## #     # #     # #     # 
  #####  #     #  #####  ######   #####  
#sftp module
#https://github.com/sord1d/cnsbs/


if [ "$program" = "" ]
then
echo "\e[1;91mcrtitical error. program variable not found."
echo "\e[1;91mthis module cannot be executed by the shell"
exit
else
echo "Trying to connect"
fi
      rm -r main-old
      mv main/ main-old
      rm -r creative-old
      mv creative/ creative-old
      rm -r pandora-old
      mv pandora/ pandora-old
      rm -r island-old
      mv island/ island-old
      
     sftp -i $private -P $port $server << EOF
      get -r servers/creative/worlds creative/
      get -r servers/pandora/worlds pandora/
      get -r servers/bentobox/worlds island/
      get -r servers/main/worlds main/
      EOF


